[build]
target = "riscv32imc-unknown-none-elf"      # change this by 'set-target.sh'

rustflags = [
    # "Required to obtain backtraces, however it may negatively impact the performance of your application."
    #
    # Note: Interesting discussion in:
    #   - "`force-frame-pointers` flag isn't honored always unless std is recompiled as such"
    #       -> https://github.com/rust-lang/rust/issues/103711 (GitHub Issues; [closed])
    #
    # tbd. find out if there's (really no?) way to declare this in 'build.rs'.
    "-C", "force-frame-pointers",
]

[target.'cfg(all())']   # unconditional '[target]' #hack
runner = ["probe-rs", "run", "--log-format={L} {s}"]
    #
    # Note: Using the '[...]' format is the ONLY WAY that a space can be expressed in the '--log-format' syntax!
    #
    # Note: The author wasn't able to place a space in the '--log-format'. Tried:
    #       "[...] --log-format '{L} {s}'"
    #       "[...] --log-format \"{L} {s}\""
    #       '[...] --log-format "{L} {s}"'
    #       "[...] --log-format {L}\ {s}"
    #       '[...] --log-format {L}\ {s}'
    #       '[...] --log-format {L} {s}'    # NBSP
    #
    # For syntax, see -> https://defmt.ferrous-systems.com/custom-log-output#metadata-specifiers
